version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../public:/var/www/html
      - ../src:/var/www/src
      - ../public/uploads:/var/www/html/uploads
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yemek_yonetim_sistemi
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db